version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'andron13'
    commit-message:
      prefix: 'chore'
    ignore:
      - dependency-name: 'eslint'
        update-types: ['version-update:semver-major']
